kind: pipeline
name: default

steps:
  - name: backend
    image: golang
    commands:
      - go build
      - go test
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: dev
      icon_url: https://unsplash.it/256/256/?random
