kind: pipeline
name: default

steps:
  - name: backend
    image: golang
    commands:
      - go build
      - go test
      - go test -race -coverprofile=coverage.txt -covermode=atomic
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov-token
      files:
        - coverage.txt
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: dev
      icon_url: https://unsplash.it/256/256/?random
    when:
      event:
        - promote
        target:
        - production

