kind: pipeline
name: default

steps:
- name: backend
  image: golang
  commands:
  - go build
  - go test

- name: telegram
  image: appleboy/drone-telegram
  token:
    from_secret: tgtoken
  to: -303479375
